services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - E:\AI\comfyui:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    restart: always

#  comfyui-boot:
#    image: yanwk/comfyui-boot:cu124-slim
#    container_name: comfyui
#    stdin_open: true
#    tty: true
#    ports:
#      - 8188:8188
#    volumes:
#      - 'E:\AI\comfyui:/root'
#    deploy:
#      resources:
#        reservations:
#          devices:
#            - driver: nvidia
#              count: all
#              capabilities:
#                - gpu
#    restart: always

  openwebui:
    image: ghcr.io/open-webui/open-webui:cuda
    container_name: open-webui
    ports:
      - "3000:8080"
    environment:
      - OLLAMA_BASE_URL=http://host.docker.internal:11434
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - open-webui:/app/backend/data
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    restart: always

volumes:
  ollama:
  open-webui: