services:
  vllm:
    image: vllm/vllm-openai:latest
    hostname: vllm
    container_name: vllm
    command: 
      - ${VLLM_MODEL}
    environment:
      - HUGGING_FACE_HUB_TOKEN=${HF_TOKEN}
    volumes:
      - ${VLLM_CACHE_DIR}:/root/.cache/huggingface
    security_opt:
      - "label=type:nvidia_container_t"
    devices:
      - nvidia.com/gpu=all # If there are multiple GPUs and the wrong one runs, then disable one on the host.
    ipc: host # allow the container to access the host's shared memory
    restart: unless-stopped

  openwebui:
    image: ghcr.io/open-webui/open-webui:cuda
    hostname: open-webui
    container_name: open-webui
    ports:
      - "${Openwebui_Port}:8080"
    environment:
      - OPENAI_API_BASE_URL=http://vllm:8000/v1
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - open-webui:/app/backend/data
    restart: unless-stopped

volumes:
  open-webui: